error: function does not abort under this condition
  ┌─ /home/user/solidity-vs-move-verification/contracts/bank/move/sources/bank_apt.spec.move:6:9
  │
6 │         aborts_if !exists<coin::CoinStore<AptosCoin>>(signer::address_of(sender));
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │
error: function does not abort under this condition
  ┌─ /home/user/solidity-vs-move-verification/contracts/bank/move/sources/bank_apt.spec.move:7:9
  │
7 │         aborts_if !global<coin::CoinStore<AptosCoin>>(signer::address_of(sender)).frozen;
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │
error: abort not covered by any of the `aborts_if` clauses
    ┌─ /home/user/solidity-vs-move-verification/contracts/bank/move/sources/bank_apt.spec.move:3:5
    │  
  3 │ ╭     spec withdraw {
  4 │ │         aborts_if amount == 0;
  5 │ │         aborts_if !exists<Bank>(bank);
  6 │ │         aborts_if !exists<coin::CoinStore<AptosCoin>>(signer::address_of(sender));
    · │
 30 │ │ 
 31 │ │     }
    │ ╰─────^
    │  
    ┌─ /home/user/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-framework/sources/coin.move:797:13
    │
797 │             assert!(
    │             ------ abort happened here with code 0x5
{
  "Error": "Move Prover failed: exiting with verification errors"
}
